### ISSUE TITLE
Update for the Django 1.8 and 1.9 + Foundation 6 support 

### ISSUE THREAD

**Issue by gustavi** [django-blog-zinnia/zinnia-theme-foundation#1]
Must be ready for the next version of django-blog-zinnia (wich support Django 1.7).

An example : https://github.com/Fantomas42/django-blog-zinnia/commit/96176e10acd1c5b278a6e37885fc1140b16ee31b

**Comment by Fantomas42** [comment]
Hi @gustavi 
I see that bc4c9bf7dbcddcd06de8dc98a68eff49afad7d82 has fixed the issue.

Can you do a new release on Pypi of the package ?

Regards

**Comment by gustavi** [comment]
I was AFK for a long time. I'll fix this in next days.

**Comment by Fantomas42** [comment]
Great !

**Comment by Fantomas42** [comment]
Hello @gustavi 

how are you ?

could you do a new release or give me the **owner** rights on Pypi for the package ?

Because the situation is blocked. :)

Regards

**Comment by gustavi** [comment]
I'll work on this soon. If no news in one month, ping me and I give you rights on Pypi :)

Sorry, lot of work at the moment !

**Comment by Fantomas42** [comment]
No problems, I understand !

**Comment by vikcon** [comment]
I am new to Django, But comfortable with Foundation. 
Can you please suggest if I can help in this?
Also is this Foundation 6 or Foundation 5?

**Comment by Fantomas42** [comment]
Hi, @gustavi 

how are you ?

Can you give me the rights on Pypi ?

Best regards

**Comment by gustavi** [comment]
Done

**Comment by Fantomas42** [comment]
Thanks @gustavi 

I've made a new release accordingly.
