### ISSUE TITLE
error with search

### ISSUE THREAD

**Issue by bradrice** [django-blog-zinnia/zinnia-theme-foundation#3]
I'm getting tis on my search:

NoReverseMatch at /blog/search/

This is what I have for blog in urls:

url(r'^blog/', include('zinnia.urls', namespace='zinnia')),
url(r'^comments/', include('django_comments.urls')),
url(r'^ckeditor/', include('ckeditor.urls')),

Here is my site:

http://www.bradrice.com/blog/

Can you tell me if this is a bug or if I need to configure my installation?

**Comment by Fantomas42** [comment]
Quick fixed in https://github.com/django-blog-zinnia/zinnia-theme-foundation/commit/cd5140ca4cc68c5acdf77bf02b3b9eba64b5e8ea

**Comment by Fantomas42** [comment]
Related to #1
