### ISSUE TITLE
TemplateNotFound

### ISSUE THREAD

**Issue by bradrice** [django-blog-zinnia/zinnia-theme-foundation#5]
Why do I get zinnia:zinnia templates are not found?

This shows up in my path for Template-loader
 /home/bradrice/lib/python3.4/zinnia_foundation/templates/zinnia:zinnia/

If I remove the :zinnia I see the templates.

Exception Type: | TemplateDoesNotExist
-- | --
zinnia:zinnia/entry_archive.html

**Comment by Fantomas42** [comment]
Hello,

you must add app_namespace.Loader in your TEMPLATES settings:
```

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'OPTIONS': {
            'loaders': [
                'app_namespace.Loader',
		'django.template.loaders.app_directories.Loader',
            ],
    }
}

Regards
```
